[codestyle]
indent_type = 'space'
indent_width = 4
workspace_dir='/home/ryosuke/proj/procon/AtCoder'
lang='cpp'
template_file='/home/ryosuke/proj/procon/AtCoder/template.cpp'
code_generator_toml='/home/ryosuke/proj/procon/AtCoder/cpp_code_generator.toml'

[etc]
download_without_login=false
parallel_download=false
save_no_session_cache=false